package sets_maps05.after;

import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

public class SetMain {
    public static void main(String... args) {
        /*
        when youre adding the value to a hashset
         its adding th hash as the key ( a unique int generated by hashcode method)
        Hashset is indexed by hash and its not ordered,
        no duplicates
         */
        Set<Integer> primeNumbers1 = new HashSet<>();

        /*
        Ordered, values are ordered as they are added
        smaller value to the left, bigger value to the right
         */
        Set<Integer> primeNumbers2 = new TreeSet<>();

        primeNumbers1.add(71);
        primeNumbers1.add(61);
        primeNumbers1.add(41);
        primeNumbers1.add(1);

        primeNumbers2.add(71);
        primeNumbers2.add(61);
        primeNumbers2.add(41);
        primeNumbers2.add(1);

        primeNumbers1.forEach(System.out::println);
        System.out.println("");
        primeNumbers2.forEach(System.out::println);

        System.out.println(primeNumbers1.add(5));
        System.out.println(primeNumbers1.add(5));

        primeNumbers1.remove(5);
        System.out.println(primeNumbers1.isEmpty());
        System.out.println(primeNumbers1.size());

    }

}
